### PR TITLE
Re-introduce the infinite loop

### LINKED ISSUE #14: Keep connection alive in SSE endpoint
**Description**
Upon making a request to the `/api/sse` endpoint, the connection is immediately closed.

**Reproduction**
Steps to reproduce the behaviour:
1. Run the server
2. Select the appropriate serial port
3. Open [`https://localhost:7097/api/sse`](https://localhost:7097/api/sse) in any browser
4. The window remains blank (and doesn't display as loading, suggesting the connection has been closed)

CURL can also be used to check what's happening, again confirming the connection is immediately closed:
1. Run the server
2. Select the appropriate serial port
3. Open a new console window
4. Run `curl -N --verbose localhost:7097/api/sse`
The output is as follows:
```sh
$ curl -N --verbose localhost:7097/api/sse
* Host localhost:7097 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:7097...
* Connected to localhost (::1) port 7097
* using HTTP/1.x
> GET /api/sse HTTP/1.1
> Host: localhost:7097
> User-Agent: curl/8.11.1
> Accept: */*
>
* abort upload
* Empty reply from server
* shutting down connection #0
curl: (52) Empty reply from server
```

**Expected behaviour**
The connection should be kept alive indefinitely, until either the client closes it or the server is shut down.

**System info**
 - OS: Windows 10 64-bit
 - .NET version: `8.0.400`

**Possible causes**
This bug must have been introduced by 8d69f0353fe8290fde6ebac0db1bb7c934177733, but for some inexplicable reason it only manifested recently. Running a `git bisect` might give some insight into when exactly this bug started manifesting. However, the root cause must be that the endpoint handler is returning, and ASP.NET interprets that as permission to close the connection. Thus, fixing this bug is easy: just never return from `ServerEventController.SSE()`. Unfortunately, things aren't that simple: that function originally had an infinite loop, which was found to be the cause of #5. Discussion regarding that issue should be taken into account when trying to fix this bug.

**Additional context**
Branch [`hotfix-schema`](https://github.com/orbisat-oeiras/backend/tree/hotfix-schema) contains a quick fix - it just re-introduces the infinite loop.

**Logs**
```log
2025-03-08T17:21:12.3711501+00:00	INFO	[Microsoft.Hosting.Lifetime]	[ListeningOnAddress]	Now listening on: https://localhost:7097
2025-03-08T17:21:12.3729377+00:00	INFO	[Microsoft.Hosting.Lifetime]	[ListeningOnAddress]	Now listening on: http://localhost:5199
2025-03-08T17:21:12.4074055+00:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
2025-03-08T17:21:12.4079653+00:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Development
2025-03-08T17:21:12.4080326+00:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: D:\escola\20242025\clube\cansat\backend\Server
2025-03-08T17:21:16.1363194+00:00	INFO	[backend.Server.Controllers.ServerEventsController]	[0]	DI provided 6 event finalizers.
2025-03-08T17:21:16.1396642+00:00	WARN	[Microsoft.AspNetCore.Server.Kestrel]	[InvalidResponseHeaderRemoved]	One or more of the following response headers have been removed because they are invalid for HTTP/2 and HTTP/3 responses: 'Connection', 'Transfer-Encoding', 'Keep-Alive', 'Upgrade' and 'Proxy-Connection'.
2025-03-08T17:21:16.6399463+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Receiving...
2025-03-08T17:21:16.6417571+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	LINE: [2689269]:[140547.42]:[-124.66];

2025-03-08T17:21:17.1482313+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Receiving...
2025-03-08T17:21:17.1487164+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	LINE: schema[timestamp]:[pressure]:[temperature]

2025-03-08T17:21:17.1494638+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Schema: [timestamp]:[pressure]:[temperature]

2025-03-08T17:21:17.6386042+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Receiving...
2025-03-08T17:21:17.6398138+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	LINE: [2689815]:[140547.42]:[-124.66];

2025-03-08T17:21:18.1425914+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Receiving...
2025-03-08T17:21:18.1449149+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	LINE: [2690315]:[140547.42]:[-124.66];

2025-03-08T17:21:18.6455870+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Receiving...
2025-03-08T17:21:18.6457831+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	LINE: [2690814]:[140547.42]:[-124.66];

2025-03-08T17:21:19.1364290+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Receiving...
2025-03-08T17:21:19.1366761+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	LINE: [2691315]:[140547.42]:[-124.66];

2025-03-08T17:21:19.6403728+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Receiving...
2025-03-08T17:21:19.6405373+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	LINE: [2691815]:[140547.42]:[-124.66];

2025-03-08T17:21:20.1391718+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Receiving...
2025-03-08T17:21:20.1393135+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	LINE: [2692315]:[140547.42]:[-124.66];

2025-03-08T17:21:20.6482279+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	Receiving...
2025-03-08T17:21:20.6484541+00:00	INFO	[backend.Library.Services.DataProviders.SerialProvider]	[0]	LINE: [2692814]:[140547.42]:[-124.66];
```

### PR DESCRIPTION
**Pull request by mslago**
As referenced in #15, the server crashes when connecting to the API. 
To fix this, we've re-established the infinite loop in the ServerEventsController.cs file.
Will close #14

### CODE REVIEW

File: Server/Controllers/ServerEventsController.cs [hunk 1]
```diff
@@ -43,32 +44,57 @@ IEnumerable<IFinalizedProvider> eventFinalizers
...
+            try
             {
-                // Subscribe to finalizers
-                eventFinalizer.OnDataProvided += async payload =>
+                foreach (IFinalizedProvider eventFinalizer in _eventFinalizers)
                 {
-                    // Leaving these here just in case...
-                    //_logger.LogInformation("Sending event provided by {evtFinalizerType}.", eventFinalizer.GetType().Name);
-                    //_logger.LogDebug("Tag: {tag}\nContent: {content}", payload.Data.tag, payload.Data.content);
+                    async void handler(EventData<(string tag, object content)> payload)
```
Comment (levimcgomes) [inline Server/Controllers/ServerEventsController.cs:59]:
```suggestion
                    async void Handler(EventData<(string tag, object content)> payload)
```

File: Server/Controllers/ServerEventsController.cs [hunk 2]
```diff
@@ -43,32 +44,57 @@ IEnumerable<IFinalizedProvider> eventFinalizers
...
+                        await Response.WriteAsync($"data: ");
+                        // Convert the content to JSON
+                        await Response.WriteJSONAsync(payload.Data.content);
+                        await Response.WriteAsync("@");
+                        await Response.WriteJSONAsync(payload.DataStamp);
+                        await Response.WriteAsync("\n\n");
+                        await Response.Body.FlushAsync();
+                    }
+                    eventFinalizer.OnDataProvided += handler;
+                    eventHandlers.Add(handler);
```
Comment (levimcgomes) [inline Server/Controllers/ServerEventsController.cs:80]:
```suggestion
                    eventFinalizer.OnDataProvided += Handler;
                    eventHandlers.Add(Handler);
```

File: Server/Controllers/ServerEventsController.cs [hunk 3]
```diff
@@ -43,32 +44,57 @@ IEnumerable<IFinalizedProvider> eventFinalizers
...
+            {
+                foreach (IFinalizedProvider eventFinalizer in _eventFinalizers)
+                {
+                    foreach (
+                        Action<EventData<(string tag, object content)>> handler in eventHandlers
+                    )
+                    {
+                        eventFinalizer.OnDataProvided -= handler;
+                    }
+                }
```
Comment (levimcgomes) [inline Server/Controllers/ServerEventsController.cs:97]: This just feels wrong. The way things are built, there is exactly one handler per finalizer, so we shouldn't remove each handler from each finalizer. Even if the performance cost isn't that big of a deal, there still has to be a better way to do this. Perhaps a dict is the way to go, or we can just trust that everything happens *in order* and zip the two lists together.

**Review by levimcgomes — COMMENTED** [review]
After a quick test, this seems to be in a middleground: neither can the browser get a connection, neither does the server shutdown immediatelly on ^C!

Seriously though, is it working for you? Can you please test it? I'll also try to test it a bit more thoroughly soon.

**Comment by mslago** [comment]
You're right. Just tested without the mock data provider, it seems to not connect. I think this behaviour is due to the serial port sending out nothing, so the server doesn't actually send out proper data. I'll try reverting to what I had before with the cancellation token and check whether I can ctrl+c out of that.

**Comment by mslago** [comment]
Yeah so after merging #15 and #16 in my fork things don't quite work as expected, it gives me an error right after connecting which I'll look more into. I'll try fixing everything tomorrow.

**Comment by mslago** [comment]
Apparently when introducing a [CancellationToken](https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-7.0#cancellationtoken) inside an API Action, the token just turns to `false` when the connection is interrupted. Not when we Ctrl+C out of the program, as we had previously thought. That means the implementation of a cancellationtoken inside the SSE action means that we can **just** stop the program when the HTTP connection is stopped.

**Comment by mslago** [comment]
It works! After merging with the [mockserialdata](https://github.com/orbisat-oeiras/backend/tree/mockserialdata) branch, you should have everything working correctly.

**Comment by mslago** [comment]
About [a77d7cf](https://github.com/orbisat-oeiras/backend/pull/16/commits/a77d7cfb8b95c5be88d4ce64c47cebaebd3c63b9): Do we want the server to keep running after we lose connection? I'm open to suggestions. Right now, this also allows for multiple connections. 
Before [a77d7cf](https://github.com/orbisat-oeiras/backend/pull/16/commits/a77d7cfb8b95c5be88d4ce64c47cebaebd3c63b9), if we had multiple clients connected to our server, just one failing would cause the entire server to crash. Now, though exceptions get thrown when one client disconnects, the server is still able to keep sending out data to other live clients. This may sound a bit confusing so we gotta talk more about this later. 
Complications aside, it works!

**Comment by levimcgomes** [comment]
I've detected another bug which was actually interfering with my tests of this fix: this [`if` statement](https://github.com/orbisat-oeiras/backend/blob/a77d7cfb8b95c5be88d4ce64c47cebaebd3c63b9/Library/Services/DataProviders/SerialProvider.cs#L127) is outdated - we have since decided serial devices needn't provide a complete dataset, which inherently means schemas should be allowed to be 'incomplete'. I'll try to fix this - it shouldn't be too hard.

File: Server/Controllers/ServerEventsController.cs [hunk 4]
```diff
@@ -43,33 +45,57 @@ IEnumerable<IFinalizedProvider> eventFinalizers
...
+                        await Response.WriteJSONAsync(payload.DataStamp);
+                        await Response.WriteAsync("\n\n");
+                        await Response.Body.FlushAsync();
+                    }
+                    catch (Exception e)
+                    {
+                        _logger.LogError(
+                            e,
+                            "Error in SSE connection. The client may have disconnected."
+                        );
```
Comment (levimcgomes) [inline Server/Controllers/ServerEventsController.cs:88]: Since this doesn't *crash* the server - and is to some extent normal behaviour, I think logging it as an error might be too harsh. Also, since it's normal, it shouldn't be this verbose.
```suggestion
                        _logger.LogWarning(
                            "Error in SSE connection. The client may have disconnected."
                        );
```
Also, maybe only the exception type that comes from a client disconnecting should be caught.

File: Server/Controllers/ServerEventsController.cs [hunk 5]
```diff
@@ -43,33 +45,57 @@ IEnumerable<IFinalizedProvider> eventFinalizers
...
+                    }
                 };
             }
+
+            // Keep the connection open until the client disconnects
+            // This keeps the data generation loop running, even though the client is not connected
+            // This also just works, I'm not sure why
+            cancellationToken.WaitHandle.WaitOne();
+            tcs.TrySetResult();
+            await tcs.Task;
```
Comment (levimcgomes) [inline Server/Controllers/ServerEventsController.cs:98]: I have absolutely no idea how or even why this works - it seems like it should return instantly, yet somehow my tests suggest it doesn't. However, given that the to-be-added CSV generator will be able to continuously keep the data generation loop running, why don't we allow this to stop when the client disconnects?

**Review by levimcgomes — APPROVED** [review]

**Review by levimcgomes — APPROVED** [review]
